source 'https://github.com/CocoaPods/Specs.git' # 公有源
source 'https://github.com/NJHu/NJSpecs.git' # NJ 私有源

use_frameworks!

target 'NJMediator_NJSisVideoList_Example' do
  pod 'NJMediator_NJSisVideoList', :path => '../'

  target 'NJMediator_NJSisVideoList_Tests' do
    inherit! :search_paths

    
  end
end
